[project]
name = "repl-nix-imageanalyzerpro"
version = "0.1.0"
description = "Theory of Constraints Full-Kit Puzzle Game"
requires-python = ">=3.11"
dependencies = [
    "flask>=3.1.0",
    "pillow>=11.0.0",
    "requests>=2.31.0",
    "werkzeug>=3.0.1",
    "gunicorn>=21.2.0"
]
